alias gst="git status -s"
alias gad="git add"
alias gai="git add -i"
alias gap="git add -p"
alias glg="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gcm="git commit -m"
alias gch="git cherry-pick"
alias gco="git checkout"
