#! /usr/bin/env bash

BACK=$(pwd)
cd $HOME/.parts/autoparts && git pull && cd $BACK
parts install postgresql redis tree tmux heroku-cli uuid 
echo "parts start postgresql redis" >> $HOME/workspace/startup.sh
