#! /usr/bin/env bash

# Setup repositories
sudo apt-add-repository -y ppa:chris-lea/node.js
sudo apt-add-repository -y ppa:git-core/ppa
sudo apt-get update

# Package per line easier to maintain
sudo apt-get install -y \
git\ 
tmux \
vim-nox \
nodejs \
redis-server \
build-essential \
postgresql-9.3 \
postgreseql-contrib-9.3 \
libpq-dev

# Link configs
ln -s ~/dotfiles/vimrc ~/.vimrc
ln -s ~/dotfiles/tmux.conf ~/.tmux.conf
